#!/usr/bin/env bash

# By Jonathan

# --------------------------------------------PARÂMETROS-------------------------------------------- #
# Cores
cyan=`tput setaf 6 ; tput bold`
green=`tput setaf 2 ; tput bold`
red=`tput setaf 1 ; tput bold`
yellow=`tput setaf 3 tput bold`
blink=`tput blink`
bold=`tput sgr0 ; tput bold`

# Diretórios
DIRETORIO_DOWNLOADS="$HOME/Downloads/temp"

# URLs
LIBRE_EXTENSION="https://extensions.libreoffice.org/assets/downloads/z/veroptbrv320aoc.oxt" 

# -------------------------------VERIFICAÇÃO DE USUÁRIO ROOT------------------------------- #
# Verificando o login do usuário
if [ $LOGNAME = "root" ]; then
    # Se for igual a root, imprime a mensagem de errolj
    	echo "${cyan}[Terminal] ${red}${blink}Execute sem sudo. :("  ; sleep 4 && clear
    	exit 1
fi

# --------------------------------------------INTRODUÇÃO-------------------------------------------- #
echo -n "${cyan}[Terminal] ${bold}Iniciando o script"
sleep 0.7 ; echo -n "."
sleep 0.7 ; echo -n "."
sleep 0.7 ; echo -n "."
sleep 0.5
clear

# ---------------------------------------TESTES E REQUISITOS---------------------------------------- #
# Teste de conexão com internet
if ! ping -c 1 8.8.8.8 -q &> /dev/null; then
	echo -e "${red}[Terminal]  ${bold}Seu computador não tem conexão com a Internet. Verifique a rede."
  exit 1
else
  echo -e "${green}[Terminal] ${bold}Conexão com a Internet funcionando normalmente."
fi

# -------------------------------------ATUALIZAÇÃO DO SISTEMA--------------------------------------- #
# Atualizando repositório e sistema
sleep 1 ; echo -e "
${cyan}[Terminal] ${bold}Atualizando o sistema."
sudo dnf up -y

Fazer o melhor com a nossa melhor realidade para que possamos ter uma realidade melhor e fazer melhor ainda.

# -----------------------------------INSTALAÇÃO DE REPOSITÓRIOS------------------------------------- #
# Instalação RPM Fusion
echo -e "
${cyan}[Terminal] ${bold}Instalando RPM Fusion."
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
sudo dnf install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y

# Adição do repositório do Google Chrome
echo -e "
${cyan}[Terminal] ${bold}Adicionando repositório do Google Chrome."
sudo dnf config-manager --set-enabled google-chrome ; sleep 1
 
# -------------------------------------------INSTALAÇÃO--------------------------------------------- #
# Instalação de programas pelo DNF
PROGRAMAS_PARA_INSTALAR=(
   gnome-tweaks
   google-chrome-stable
   vlc
   tlp
   java
   ffmpeg
   pdfarranger
   menulibre
   youtube-dl
   neofetch
   calibre
   transmission
   snes9x-gtk
   telegram-desktop
   steam
   papirus-icon-theme
   zsh
   util-linux-user 
   p7zip 
   p7zip-plugins 
   lzip 
   cabextract 
   unrar
   python
   gnome-calendar
   shotcut
   libreoffice-math
   qwinff
)

for nome_do_programa in ${PROGRAMAS_PARA_INSTALAR[@]}; do
	if ! rpm -qa | grep -q $nome_do_programa; then # Só instala se já não estiver instalado
		echo -e "
${cyan}[Terminal] ${bold}Instalando ${yellow}"$nome_do_programa"${bold}." ; sudo dnf install "$nome_do_programa" -y
	else
		echo -e "
${cyan}[Terminal] ${bold}Instalado ${yellow}"$nome_do_programa"${bold}."
  	fi
done

# Instalando pacotes Flatpak
echo -e "
${cyan}[Terminal] ${bold}Instalando programas em Flatpak."
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.spotify.Client -y

# Download e instalaçao de programas externos
echo -e "
${cyan}[Terminal] ${bold}Baixando arquivos."
mkdir "$DIRETORIO_DOWNLOADS"
wget -c "$LIBRE_EXTENSION" -P "$DIRETORIO_DOWNLOADS"

# Fim
echo -n "${cyan}[Terminal] ${bold}Instalação concluída."
exit 1
